name: metteghijsen

version: "3.9"
services:
  web:
    build: .
    image: metteghijsen/web:latest
    ports:
      - "${PORT:-}:80"
    deploy:
      replicas: 1
      update_config:
        order: start-first
        parallelism: 1
        delay: 5s
        failure_action: rollback
        monitor: 30s
      restart_policy:
        condition: on-failure
